name: Get Proxy

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
    
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp geoip2 beautifulsoup4
          
      - name: Pull files
        run: |
          git config --global user.email "lnikolai228@gmail.com"
          git config --global user.name "Vadim287"
          git pull origin main
      
      - name: Get proxies
        run: python getproxy.py

      - name: Check updated proxies
        run: ls -la proxies

      - name: Commit files
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update Proxies (`date '+%F %H:%M %Z'`)" -a
          else
            echo "No changes to commit"
          fi
          git branch -u origin/main
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main
